name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    strategy:
      matrix: 
        app: [alerter, console, elasticsearch, logstash, zipkin, import-dashboards, curator]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker version
        docker compose version
        docker build -f jhipster-${{matrix.app}}/Dockerfile -t duderoot/jhipster-${{matrix.app}}:travis jhipster-${{matrix.app}}/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to Docker Registry
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      # if: ${{env.DOCKERHUB_USERNAME != '' && startsWith(github.ref, 'refs/tags/v')}}
      uses: docker/login-action@v2.1.0
      id: login-hub
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true #${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
