name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  
  build:
    strategy:
      matrix: 
        app: [alerter, console, elasticsearch, logstash, zipkin, import-dashboards, curator]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        docker version
        docker compose version
        docker build -f jhipster-${{matrix.app}}/Dockerfile -t duderoot/jhipster-${{matrix.app}}:travis jhipster-${{matrix.app}}/